export const RequestData = {
  allreq: [
    { name: "Amit Sharma", email: "cse22001@iiitkalyani.ac.in", reg_no: 845, receipt: "https://example.com/receipt1.pdf" },
    { name: "Priya Verma", email: "cse22002@iiitkalyani.ac.in", reg_no: 912, receipt: "https://example.com/receipt2.pdf" },
    { name: "Rahul Gupta", email: "cse22003@iiitkalyani.ac.in", reg_no: 876, receipt: "https://example.com/receipt3.pdf" },
    { name: "Sneha Patel", email: "cse22004@iiitkalyani.ac.in", reg_no: 934, receipt: "https://example.com/receipt4.pdf" },
    { name: "Vikram Singh", email: "cse22005@iiitkalyani.ac.in", reg_no: 899, receipt: "https://example.com/receipt5.pdf" },
    { name: "Anjali Yadav", email: "cse22006@iiitkalyani.ac.in", reg_no: 967, receipt: "https://example.com/receipt6.pdf" },
    { name: "Suresh Nair", email: "cse22007@iiitkalyani.ac.in", reg_no: 888, receipt: "https://example.com/receipt7.pdf" },
    { name: "Kiran Rao", email: "cse22008@iiitkalyani.ac.in", reg_no: 920, receipt: "https://example.com/receipt8.pdf" },
    { name: "Pooja Iyer", email: "cse22009@iiitkalyani.ac.in", reg_no: 853, receipt: "https://example.com/receipt9.pdf" },
    { name: "Manoj Deshmukh", email: "cse22010@iiitkalyani.ac.in", reg_no: 915, receipt: "https://example.com/receipt10.pdf" },
    { name: "Arjun Malhotra", email: "cse22011@iiitkalyani.ac.in", reg_no: 870, receipt: "https://example.com/receipt11.pdf" },
    { name: "Neha Joshi", email: "cse22012@iiitkalyani.ac.in", reg_no: 942, receipt: "https://example.com/receipt12.pdf" },
    { name: "Rajeev Choudhary", email: "cse22013@iiitkalyani.ac.in", reg_no: 858, receipt: "https://example.com/receipt13.pdf" },
    { name: "Divya Tiwari", email: "cse22014@iiitkalyani.ac.in", reg_no: 893, receipt: "https://example.com/receipt14.pdf" },
    { name: "Aakash Mehta", email: "cse22015@iiitkalyani.ac.in", reg_no: 975, receipt: "https://example.com/receipt15.pdf" },
    { name: "Swati Reddy", email: "cse22016@iiitkalyani.ac.in", reg_no: 818, receipt: "https://example.com/receipt16.pdf" },
    { name: "Rohit Bansal", email: "cse22017@iiitkalyani.ac.in", reg_no: 861, receipt: "https://example.com/receipt17.pdf" },
    { name: "Meera Nambiar", email: "cse22018@iiitkalyani.ac.in", reg_no: 910, receipt: "https://example.com/receipt18.pdf" },
    { name: "Kunal Aggarwal", email: "cse22019@iiitkalyani.ac.in", reg_no: 928, receipt: "https://example.com/receipt19.pdf" },
    { name: "Ramesh Das", email: "cse22020@iiitkalyani.ac.in", reg_no: 845, receipt: "https://example.com/receipt20.pdf" },
    { name: "Shweta Mukherjee", email: "cse22021@iiitkalyani.ac.in", reg_no: 887, receipt: "https://example.com/receipt21.pdf" },
    { name: "Nikhil Saxena", email: "cse22022@iiitkalyani.ac.in", reg_no: 933, receipt: "https://example.com/receipt22.pdf" },
    { name: "Varun Kapoor", email: "cse22023@iiitkalyani.ac.in", reg_no: 951, receipt: "https://example.com/receipt23.pdf" },
    { name: "Tanvi Shah", email: "cse22024@iiitkalyani.ac.in", reg_no: 899, receipt: "https://example.com/receipt24.pdf" },
    { name: "Deepak Chatterjee", email: "cse22025@iiitkalyani.ac.in", reg_no: 924, receipt: "https://example.com/receipt25.pdf" },
    { name: "Sonia Pillai", email: "cse22026@iiitkalyani.ac.in", reg_no: 978, receipt: "https://example.com/receipt26.pdf" },
    { name: "Aditya Narayan", email: "cse22027@iiitkalyani.ac.in", reg_no: 844, receipt: "https://example.com/receipt27.pdf" },
    { name: "Bhavna Shetty", email: "cse22028@iiitkalyani.ac.in", reg_no: 927, receipt: "https://example.com/receipt28.pdf" },
    { name: "Gopal Menon", email: "cse22029@iiitkalyani.ac.in", reg_no: 852, receipt: "https://example.com/receipt29.pdf" },
    { name: "Madhuri Dutta", email: "cse22030@iiitkalyani.ac.in", reg_no: 965, receipt: "https://example.com/receipt30.pdf" },
    { name: "Ravindra Pandey", email: "cse22031@iiitkalyani.ac.in", reg_no: 811, receipt: "https://example.com/receipt31.pdf" }
  ]
};
